;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region-or-backward-word
        smart-line-beginning
        ))

(setq mc/cmds-to-run-once
      '(
        mouse-major-mode-menu
        ))
