;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        sgml-slash
        tagedit-forward-slurp-tag
        tagedit-insert-hash
        tagedit-insert-lt
        tagedit-insert-quote
        ))

(setq mc/cmds-to-run-once
      '(
        tagedit-insert-gt
        ))
